/**
 * @fileoverview gRPC-Web generated client stub for trezoitao
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v5.27.1
// source: 38tao.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.trezoitao = require('./38tao_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.trezoitao.TrezoitaoServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.trezoitao.TrezoitaoServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.trezoitao.GiveMeBTCRequest,
 *   !proto.trezoitao.GiveMeBTCResponse>}
 */
const methodDescriptor_TrezoitaoService_GetBTC = new grpc.web.MethodDescriptor(
  '/trezoitao.TrezoitaoService/GetBTC',
  grpc.web.MethodType.UNARY,
  proto.trezoitao.GiveMeBTCRequest,
  proto.trezoitao.GiveMeBTCResponse,
  /**
   * @param {!proto.trezoitao.GiveMeBTCRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.trezoitao.GiveMeBTCResponse.deserializeBinary
);


/**
 * @param {!proto.trezoitao.GiveMeBTCRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.trezoitao.GiveMeBTCResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.trezoitao.GiveMeBTCResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.trezoitao.TrezoitaoServiceClient.prototype.getBTC =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/trezoitao.TrezoitaoService/GetBTC',
      request,
      metadata || {},
      methodDescriptor_TrezoitaoService_GetBTC,
      callback);
};


/**
 * @param {!proto.trezoitao.GiveMeBTCRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.trezoitao.GiveMeBTCResponse>}
 *     Promise that resolves to the response
 */
proto.trezoitao.TrezoitaoServicePromiseClient.prototype.getBTC =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/trezoitao.TrezoitaoService/GetBTC',
      request,
      metadata || {},
      methodDescriptor_TrezoitaoService_GetBTC);
};


module.exports = proto.trezoitao;

