// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: 38tao.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TrezoitaoServiceClient is the client API for TrezoitaoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrezoitaoServiceClient interface {
	GetBTC(ctx context.Context, in *GiveMeBTCRequest, opts ...grpc.CallOption) (*GiveMeBTCResponse, error)
}

type trezoitaoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrezoitaoServiceClient(cc grpc.ClientConnInterface) TrezoitaoServiceClient {
	return &trezoitaoServiceClient{cc}
}

func (c *trezoitaoServiceClient) GetBTC(ctx context.Context, in *GiveMeBTCRequest, opts ...grpc.CallOption) (*GiveMeBTCResponse, error) {
	out := new(GiveMeBTCResponse)
	err := c.cc.Invoke(ctx, "/trezoitao.TrezoitaoService/GetBTC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrezoitaoServiceServer is the server API for TrezoitaoService service.
// All implementations must embed UnimplementedTrezoitaoServiceServer
// for forward compatibility
type TrezoitaoServiceServer interface {
	GetBTC(context.Context, *GiveMeBTCRequest) (*GiveMeBTCResponse, error)
	mustEmbedUnimplementedTrezoitaoServiceServer()
}

// UnimplementedTrezoitaoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTrezoitaoServiceServer struct {
}

func (UnimplementedTrezoitaoServiceServer) GetBTC(context.Context, *GiveMeBTCRequest) (*GiveMeBTCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBTC not implemented")
}
func (UnimplementedTrezoitaoServiceServer) mustEmbedUnimplementedTrezoitaoServiceServer() {}

// UnsafeTrezoitaoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrezoitaoServiceServer will
// result in compilation errors.
type UnsafeTrezoitaoServiceServer interface {
	mustEmbedUnimplementedTrezoitaoServiceServer()
}

func RegisterTrezoitaoServiceServer(s grpc.ServiceRegistrar, srv TrezoitaoServiceServer) {
	s.RegisterService(&TrezoitaoService_ServiceDesc, srv)
}

func _TrezoitaoService_GetBTC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GiveMeBTCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrezoitaoServiceServer).GetBTC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trezoitao.TrezoitaoService/GetBTC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrezoitaoServiceServer).GetBTC(ctx, req.(*GiveMeBTCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrezoitaoService_ServiceDesc is the grpc.ServiceDesc for TrezoitaoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrezoitaoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trezoitao.TrezoitaoService",
	HandlerType: (*TrezoitaoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBTC",
			Handler:    _TrezoitaoService_GetBTC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "38tao.proto",
}
